= Relaton API

This API is deployed at https://api.relaton.org for public access.

== Getting Started

image:https://github.com/relaton/api.relaton.org/actions/workflows/ci.yml/badge.svg["build, link="https://github.com/relaton/api.relaton.org/actions/workflows/ci.yml"]

== Usage

=== Fetch version

The `/api/v1/version` endpoint allow us to fetch the verions of the `api.relaton.org` through the Relaton gem.

**Request**

[source]
----
Method: GET
Endpoint: /api/v1/version
Content-Type: text/plain
Parameters: no

Example: /api/v1/version
----

Try it out, click https://api.relaton.org/api/v1/version[this link]!

**Response**

[source]
----
Version: 0.0.3, Relaton version: 1.8.pre4
----


=== Fetch bibdata of a document

The `/api/v1/document` endpoint allow us to fetch any of the supported standards.

**Request**

[source]
----
Method: GET
Endpoint: /api/v1/standard
Content-Type: application/xml
Parameters: code (required), year, all_parts, keep_year

Example: /api/v1/standard?code=ISO 19115-1&year=2011&all_parts=true,keep_year=false
```

**Response**

[source,xml]
----
<bibdata type="standard">
  <fetched>2021-07-17</fetched>
  <title type="title-intro" format="text/plain" language="en" script="Latn">Geographic information</title>
  <title type="title-main" format="text/plain" language="en" script="Latn">Metadata</title>
  <title type="title-part" format="text/plain" language="en" script="Latn">Part 1: Fundamentals</title>
  <title type="main" format="text/plain" language="en" script="Latn">Geographic information - Metadata - Part 1: Fundamentals</title>
  <title type="title-intro" format="text/plain" language="fr" script="Latn">Information géographique</title>
  <title type="title-main" format="text/plain" language="fr" script="Latn">Métadonnées</title>
  <title type="title-part" format="text/plain" language="fr" script="Latn">Partie 1: Principes de base</title>
  <title type="main" format="text/plain" language="fr" script="Latn">Information géographique - Métadonnées - Partie 1: Principes de base</title>
  <uri type="src">https://www.iso.org/standard/53798.html</uri>
  <uri type="obp">https://www.iso.org/obp/ui/#!iso:std:53798:en</uri>
  <uri type="rss">https://www.iso.org/contents/data/standard/05/37/53798.detail.rss</uri>
  <docidentifier type="ISO">ISO 19115-1</docidentifier>
  <docidentifier type="URN">urn:iso:std:iso:19115:-1:stage-90.93:ed-1:en,fr</docidentifier>
  ...
  <ext>
    <doctype>international-standard</doctype>
    <editorialgroup>
      <technical-committee number="211" type="TC">ISO/TC 211Geographic information/Geomatics</technical-committee>
    </editorialgroup>
    <ics>
      <code>35.240.70</code>
      <text>IT applications in science</text>
    </ics>
    <structuredidentifier type="ISO">
      <project-number>ISO 19115</project-number>
    </structuredidentifier>
  </ext>
</bibdata>
----

NOTE: https://github.com/relaton/relaton[Relaton] is used for the response, please check
documentation at Relaton for all supported standards.


== Development

After checking out the repo, run `bundle install` to install dependencies. Then, run `rspec` to run the tests.

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/relaton/api.relaton.org.
